# -*- coding: utf-8 -*-
"""animal-image-classification-using-deep-learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pw09eTPDqJH6T1DMp2enPCLEgCsRUvpc
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
from google.colab import files

# Load model
model = MobileNetV2(weights="imagenet")

# Upload image
uploaded = files.upload()

# Get image name
img_path = list(uploaded.keys())[0]

# Read image
img = image.load_img(img_path, target_size=(224,224))

# Display image
plt.imshow(img)
plt.axis("off")
plt.show()

# Prepare image
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# Predict
prediction = model.predict(x)

# Decode prediction
result = decode_predictions(prediction, top=3)[0]

print("\nPrediction Results:\n")
for _, name, score in result:
    print(f"{name}: {score*100:.2f}%")

