# -*- coding: utf-8 -*-
"""genetic_algorithm.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lz8E_kTy2b0G01yKNbGNTasa2kovS9X4
"""

import random

# Fitness function
def fitness(x):
    return x ** 2

# Step 1: Create initial population
population = [random.randint(0, 10) for _ in range(6)]

for generation in range(5):

    print(f"\nGeneration {generation + 1}")
    print("Population:", population)

    # Step 2: Calculate fitness
    population.sort(key=fitness, reverse=True)

    print("Best value:", population[0])
    print("Best fitness:", fitness(population[0]))

    # Step 3: Select the two best parents
    parent1 = population[0]
    parent2 = population[1]

    # Step 4: Create a new population
    new_population = [parent1, parent2]7

    while len(new_population) < 6:

        # Crossover: average of parents
        child = (parent1 + parent2) // 2

        # Mutation
        mutation = random.choice([-1, 0, 1])
        child = child + mutation

        # Keep value between 0 and 10
        child = max(0, min(10, child))

        new_population.append(child)

    population = new_population